app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Hiddify
publisher_url: https://github.com/hiddify/hiddify-next
display_name: Hiddify
create_desktop_icon: true
install_dir_name: "{autopf64}\\hiddify"
setup_icon_file: ..\..\assets\images\logo_round.ico
locales:
  - en
  - fa