name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/'
      - 'appcast.xml'
  push:
    branches:
       - main
       - dev
       - android-fix-action-bug
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/'
      - 'appcast.xml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    if: "${{!contains(github.event.head_commit.message, 'release: version')}}"
    with:
      upload-artifact: ${{ github.event_name == 'push' }}
      
